version: "3.9"
services:
  clash:
    image: dreamacro/clash:latest
    ports:
      - "7890:7890"
      - "9090:9090"
    volumes:
      - ./config:/root/.config/clash:rw
      - ./ui:/ui
    networks:
      clash:
networks:
  clash:
