version: "3.9"
services:
  clash:
    image: docker.cr.20220625.xyz/dreamacro/clash:latest
    ports:
      - "9870:7890"
      - "9090:9090"
    volumes:
      - ./config:/root/.config/clash:rw
      - ./ui:/ui
    networks:
      clash:
networks:
  clash:
