name: clash
services:
  clash:
    image: ${REGISTRY:-docker.io}/dreamacro/clash:latest
    ports:
      - "9870:7890"
      - "9090:9090"
    volumes:
      - ./config:/root/.config/clash:rw
      - ./ui:/ui
    networks:
      clash:
networks:
  clash:
