name: database
services:
  mysql:
    restart: always
    image: ${REGISTRY:-docker.io}/mysql:5.7.18
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-yourdatabase}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-setrootpassword}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_USER:-dbpassword}
      TZ: Asia/Shanghai
    volumes:
       - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  clickhouse:
    restart: always
    image:  ${REGISTRY:-docker.io}/clickhouse/clickhouse-server:25.10
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-clickhouse}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-clickhouse123456}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server

  postgresql:
    image: "${REGISTRY:-docker.io}/postgres:15.15-bookworm"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database

    ####
    ## If you want to use a `.env` file, please comment the `environment` section.
    ####

    # The `env_file` tag allows us to declare an environment file
    #env_file:
    #  - .env # The name of your environment file (the one at the repository root)

    ####
    ## If you want to persist the database data, please uncomment the lines below.
    ####

    # The `volumes` tag allows us to share a folder with our container.
    # Its syntax is as follows: [folder path on our machine]:[folder path to retrieve in the container]
    volumes:
      # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path.
      # It means that every time the repository is modifying the data inside
      # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`.
      # You don't need to create the `db-data` folder. Docker Compose will do it for you.
      - postgresql_data:/var/lib/postgresql/data/
volumes:
  mysql_data:
    driver: local
  clickhouse_logs:
    driver: local
  clickhouse_data:
    driver: local
  postgresql_data:
    driver: local